name: Newman Run

on:
  push:
    branches:
      - main

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      # Checkout do reposit贸rio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Criar diret贸rio para relat贸rios
      - name: Create dir for report
        run: mkdir testArtifacts

      # Configurar ambiente
      - name: Install Node
        uses: actions/setup-node@v3

      - name: Install Newman and reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Executar os testes
      - name: Run Test
        run: newman run "New Collection.postman_collection.json" \
          -e "Tray HarryPotter.postman_environment.json" \
          -r cli,htmlextra

      # Upload dos relat贸rios
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: newman
